apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-multitool
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
          name:  nginx-conf
        - mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          name:  nginx-conf
      - name: multitool
        image: wbitt/network-multitool
        # env:
        # - name: CONFIGMAPVAR
        #   valueFrom:
        #     configMapKeyRef:
        #       name: my-configmap
        #       key: HTTP_PORT 
        ports:
        - containerPort: 80
      volumes: 
      - name: nginx-conf
        configMap:
          name: nginx