apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - name: nginx
      protocol: TCP
      port: 9001
      targetPort: 8080
      nodePort: 30808
    - name: multitool
      protocol: TCP
      port: 9002
      targetPort: 80
      nodePort: 30080
  type: NodePort