apiVersion: v1
kind: Pod
metadata:
  name: netology-web
  labels:
    app: echo-server
spec:
  containers:
  - name: netology-web
    image: ealen/echo-server
    ports:
    - containerPort: 80
      name: http-web-svc
